TRADING_SYMBOL = "LUNCUSDT"

TRADING_TIMEFRAME = "1m"

POSITION_SIZE = 1000

HISTORICAL_CANDLE_LIMIT = 200

ENABLE_SHORTS = True

ENABLE_LONGS = True

# BINANCE FEES
MAKER_FEE = 0.001
TAKER_FEE = 0.001

# EXECUTION SIMULATION
BASE_SLIPPAGE = 0.0007
MAX_SLIPPAGE = 0.005

# LUNC NEEDS LARGE UNIT COUNTS
MAX_POSITION_SIZE = 1000000

# PORTFOLIO
START_BALANCE = 1000

# RISK
RISK_PER_TRADE = 1

MAX_ACCOUNT_EXPOSURE = 25

MAX_DRAWDOWN_PERCENT = 20

# EXCHANGE SIMULATION
ENABLE_PARTIAL_FILLS = True

ENABLE_SPREAD_SIMULATION = True

ENABLE_VOLATILITY_SLIPPAGE = True

ENABLE_LIQUIDITY_SIMULATION = True